// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  fullscreen: (value: boolean) => Promise<void>;
  close: () => Promise<void>;
}

interface EnvironmentInfo {
  qitechOs: boolean;
  qitechOsGitTimestamp?: Date;
  qitechOsGitCommit?: string;
  qitechOsGitAbbreviation?: string;
  qitechOsGitUrl?: string;
}

interface EnvironmentContext {
  getInfo: () => Promise<EnvironmentInfo>;
}

type UpdateInfo = {
  githubRepoOwner: string;
  githubRepoName: string;
  githubToken?: string;
  tag?: string;
  branch?: string;
  commit?: string;
};

type UpdateProgressReport = {
  stepId: string;
  status: "pending" | "in-progress" | "completed" | "error";
  progress?: number;
};

interface UpdateContext {
  execute: (info: UpdateInfo) => Promise<void>;
  cancel: () => Promise<void>;
  onLog: (callback: (log: string) => void) => void;
  onStart: (callback: () => void) => void;
  onEnd: (callback: () => void) => void;
  onStep: (callback: (report: UpdateProgressReport) => void) => void;
}

interface TroubleshootContext {
  rebootHmi: () => Promise<void>;
  restartBackend: () => Promise<void>;
  exportLogs: () => Promise<void>;
}

interface NixOSGeneration {
  id: string;
  name: string;
  version: string;
  current: boolean;
  date: string;
  path: string;
  kernelVersion?: string;
  description?: string;
}

interface NixOSContext {
  isNixOSAvailable: bool;
  listGenerations: () => Promise<NixOSGeneration[]>;
  setGeneration: (generationId: string) => Promise<void>;
  deleteGeneration: (generationId: string) => Promise<void>;
  deleteAllOldGenerations: () => Promise<void>;
}
declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  environment: EnvironmentContext;
  update: UpdateContext;
  troubleshoot: TroubleshootContext;
  nixos: NixOSContext;
}

// Module declarations for Vite imports
declare module "*.md?raw" {
  const content: string;
  export default content;
}

declare module "*.jpg" {
  const src: string;
  export default src;
}

declare module "*.jpeg" {
  const src: string;
  export default src;
}

declare module "*.png" {
  const src: string;
  export default src;
}

declare module "*.gif" {
  const src: string;
  export default src;
}

declare module "*.svg" {
  const src: string;
  export default src;
}
