// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}

interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  fullscreen: (value: boolean) => Promise<void>;
  close: () => Promise<void>;
}

interface EnvironmentInfo {
  qitechOs: boolean;
  qitechOsGitTimestamp?: Date;
  qitechOsGitCommit?: string;
  qitechOsGitAbbreviation?: string;
  qitechOsGitUrl?: string;
}

interface EnvironmentContext {
  getInfo: () => Promise<EnvironmentInfo>;
}

interface UpdateContext {
  execute: (params: {
    githubRepoOwner: string;
    githubRepoName: string;
    githubToken?: string;
    tag?: string;
    branch?: string;
    commit?: string;
  }) => Promise<void>;
  cancel: () => Promise<{ success: boolean; error?: string }>;
  onLog: (callback: (log: string) => void) => void;
  onEnd: (
    callback: (params: { success: boolean; error?: string }) => void,
  ) => void;
  onStep: (
    callback: (params: {
      stepId: string;
      status: "pending" | "in-progress" | "completed" | "error";
      progress?: number;
    }) => void,
  ) => void;
}

interface TroubleshootContext {
  rebootHmi: () => Promise<{ success: boolean; error?: string }>;
  restartBackend: () => Promise<{ success: boolean; error?: string }>;
  startLogStream: () => Promise<{ success: boolean; error?: string }>;
  stopLogStream: () => Promise<{ success: boolean; error?: string }>;
  onLogData: (callback: (log: string) => void) => void;
}

interface NixOSGeneration {
  id: string;
  name: string;
  version: string;
  current: boolean;
  date: string;
  path: string;
  kernelVersion?: string;
  description?: string;
}

interface NixOSContext {
  listGenerations: () => Promise<{
    success: boolean;
    generations: NixOSGeneration[];
    error?: string;
  }>;
  setGeneration: (
    generationId: string,
  ) => Promise<{ success: boolean; error?: string }>;
  deleteGeneration: (
    generationId: string,
  ) => Promise<{ success: boolean; error?: string }>;
}
declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  environment: EnvironmentContext;
  update: UpdateContext;
  troubleshoot: TroubleshootContext;
  nixos: NixOSContext;
}

// Module declarations for Vite imports
declare module "*.md?raw" {
  const content: string;
  export default content;
}

declare module "*.jpg" {
  const src: string;
  export default src;
}

declare module "*.jpeg" {
  const src: string;
  export default src;
}

declare module "*.png" {
  const src: string;
  export default src;
}

declare module "*.gif" {
  const src: string;
  export default src;
}

declare module "*.svg" {
  const src: string;
  export default src;
}
