version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: staging
    directory: "/electron"
    schedule:
      interval: "monthly"
    ignore:
    - dependency-name: "*"
      update-types:
        - "version-update:semver-minor"

  - package-ecosystem: "cargo"
    target-branch: staging
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"

  - package-ecosystem: "github-actions"
    target-branch: staging
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nix"
    target-branch: staging
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 8 * * 1-5"
