version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/electron"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-minor"]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-minor"]
