pull_request_rules:
  - name: Automatic merges
    description: Merge updates
    conditions:
      - and:
        - author = dependabot[bot]
        - files = "flake.lock"
        - check-success = "nix-check"
    actions:
      review:
      merge:

  - name: Backport from master to staging
    conditions:
      - base = master
      - merged
    actions:
      backport:
        title: "(Staging backport #{{ number }}) {{ title }}"
        ignore_conflicts: true
        branches:
          - staging

queue_rules: []
merge_queue:
  queue_controls_comment: false
  status_comments: outcomes
