[workspace]
members = ["qitech_control"]
exclude = []
resolver = "2"

[workspace.package]
license = "LGPL-3.0-only"
repository = "https://github.com/qitechgmbh/control"

[workspace.dependencies]
# --- lib ---
qitech_lib = { git = "https://github.com/qitechgmbh/qitech_lib.git", rev="2ca54835250bcc5a24e50e20aa55ffc0f264033c" }

# --- framework ---
qitech_framework = { git = "ssh://git@github.com/qitechgmbh/control-v2.git", rev = "d89e893f3ee9ed3340ab6ba8220117a331a6e931", package = "qitech_framework" }
qitech_framework_tui = { git = "ssh://git@github.com/qitechgmbh/control-v2.git", rev = "d89e893f3ee9ed3340ab6ba8220117a331a6e931", package = "qitech_framework_tui" }

[workspace.lints.clippy]
# don't lint poissbilities for let chains because they were introduces after Rust 1.86
collapsible_if = "allow"

# Lint groups (priority -1)
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pendantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
