[workspace]
members = ["qitech_control"]
exclude = []
resolver = "2"

[workspace.package]
license = "LGPL-3.0-only"
repository = "https://github.com/qitechgmbh/control"

[workspace.dependencies]
# --- lib ---
qitech_lib = { git = "https://github.com/qitechgmbh/qitech_lib.git", rev="530355c00baf6335f6085441c2a497d9ac060af6" }

# --- framework ---
qitech_framework = { git = "https://github.com/qitechgmbh/qitech_framework.git", rev="af7d588e3d867faea0b6f6d50a9f47bb58ad597c" }
qitech_framework_tui = { git = "https://github.com/qitechgmbh/qitech_framework.git", rev="af7d588e3d867faea0b6f6d50a9f47bb58ad597c" }

[workspace.lints.clippy]
# don't lint poissbilities for let chains because they were introduces after Rust 1.86
collapsible_if = "allow"

# Lint groups (priority -1)
correctness = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pendantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
