[workspace]
members = ["qitech_control", "qitech_control_core"]
exclude = []
resolver = "2"

[workspace.package]
license = "LGPL-3.0-only"
repository = "https://github.com/qitechgmbh/control"
keywords = ["ethercat", "modbus", "machine"]
categories = [""]
exclude = [".github", ".vscode"]
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
# --- internal ---
qitech_control = { path = "qitech_control" }
qitech_control_core = { path = "qitech_control_core" }

# --- lib ---
qitech_lib = { git = "https://github.com/qitechgmbh/qitech_lib.git", rev="1cb01be2b3d59cf4d4a3d26111ffbd758bf99cae" }

# --- framework ---
qitech_framework = { git = "https://github.com/qitechgmbh/qitech_framework.git", rev="8a7ae85ffea74aa68cc533c831a0f0295fb890d8" }
qitech_framework_tui = { git = "https://github.com/qitechgmbh/qitech_framework.git", rev="8a7ae85ffea74aa68cc533c831a0f0295fb890d8" }
qitech_framework_hub = { git = "https://github.com/qitechgmbh/qitech_framework.git", rev="8a7ae85ffea74aa68cc533c831a0f0295fb890d8" }

# --- external ---
tokio = "1"
tower-http = "0.6.8"
tracing = "0.1.44"
tracing-subscriber = "0.3"