export interface MaterialPreset {
  abbrev: string;
  name: string;
  bulk_density: number;
  max_moisture_pct: number;
  temp_min: number;
  temp_max: number;
  drying_time_min: number;
  drying_time_max: number;
  specific_air_volume: number;
}

export function recommendedTemp(p: MaterialPreset): number {
  return Math.floor((p.temp_min + p.temp_max) / 2);
}

export const MATERIAL_PRESETS: MaterialPreset[] = [
  // ── Standard plastics ────────────────────────────────────────────────────
  { abbrev: "ABS",          name: "Acrylonitrile Butadiene Styrene",           bulk_density: 1.05, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 85,  drying_time_min: 2.0, drying_time_max: 5.0,  specific_air_volume: 1.49 },
  { abbrev: "ABS/PA",       name: "ABS/Polyamide Blend",                       bulk_density: 1.07, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 4.0, drying_time_max: 4.0,  specific_air_volume: 2.02 },
  { abbrev: "ASA",          name: "Acrylonitrile Styrene Acrylate",             bulk_density: 1.07, max_moisture_pct: 0.10,  temp_min: 85,  temp_max: 85,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.51 },
  { abbrev: "COP/COC",      name: "Cyclic Olefin Copolymer",                   bulk_density: 1.01, max_moisture_pct: 0.01,  temp_min: 80,  temp_max: 100, drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 2.38 },
  { abbrev: "EPDM",         name: "Ethylene Propylene Diene Monomer",           bulk_density: 1.22, max_moisture_pct: 0.04,  temp_min: 90,  temp_max: 100, drying_time_min: 3.0, drying_time_max: 3.0,  specific_air_volume: 1.69 },
  { abbrev: "LCP",          name: "Liquid Crystal Polymer",                    bulk_density: 1.65, max_moisture_pct: 0.02,  temp_min: 140, temp_max: 160, drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.38 },
  { abbrev: "PA/PP",        name: "Polyamide/Polypropylene Blend",              bulk_density: 1.05, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 11",        name: "Polyamide 11",                              bulk_density: 1.04, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 1.84 },
  { abbrev: "PA 12",        name: "Polyamide 12",                              bulk_density: 1.01, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.84 },
  { abbrev: "PA 4.6",       name: "Polyamide 4.6",                             bulk_density: 1.18, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 2.40 },
  { abbrev: "PA 6",         name: "Polyamide 6",                               bulk_density: 1.13, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 2.38 },
  { abbrev: "PA 6.6",       name: "Polyamide 6.6",                             bulk_density: 1.14, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 2.38 },
  { abbrev: "PA 6.12",      name: "Polyamide 6.12",                            bulk_density: 1.06, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 2.01 },
  { abbrev: "PAA",          name: "Polyacrylic Acid",                          bulk_density: 1.43, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PAI",          name: "Polyamide-imide",                           bulk_density: 1.56, max_moisture_pct: 0.05,  temp_min: 180, temp_max: 180, drying_time_min: 3.0, drying_time_max: 3.0,  specific_air_volume: 1.84 },
  { abbrev: "PAR",          name: "Polyarylate",                               bulk_density: 1.26, max_moisture_pct: 0.02,  temp_min: 130, temp_max: 130, drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.57 },
  { abbrev: "PAS",          name: "Polyarylsulfone",                           bulk_density: 1.36, max_moisture_pct: 0.05,  temp_min: 135, temp_max: 135, drying_time_min: 4.5, drying_time_max: 4.5,  specific_air_volume: 1.73 },
  { abbrev: "PBT",          name: "Polybutylene Terephthalate",                bulk_density: 1.30, max_moisture_pct: 0.04,  temp_min: 100, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.66 },
  { abbrev: "PBT/ASA",      name: "PBT/ASA Blend",                            bulk_density: 1.24, max_moisture_pct: 0.04,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.92 },
  { abbrev: "PC",           name: "Polycarbonate",                             bulk_density: 1.20, max_moisture_pct: 0.02,  temp_min: 100, temp_max: 120, drying_time_min: 4.0, drying_time_max: 4.0,  specific_air_volume: 1.69 },
  { abbrev: "PC/ABS",       name: "Polycarbonate/ABS Blend",                  bulk_density: 1.15, max_moisture_pct: 0.02,  temp_min: 90,  temp_max: 110, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.68 },
  { abbrev: "PC/ASA",       name: "Polycarbonate/ASA Blend",                  bulk_density: 1.15, max_moisture_pct: 0.02,  temp_min: 90,  temp_max: 110, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.49 },
  { abbrev: "PC/PBT",       name: "Polycarbonate/PBT Blend",                  bulk_density: 1.22, max_moisture_pct: 0.01,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.60 },
  { abbrev: "PC/PET",       name: "Polycarbonate/PET Blend",                  bulk_density: 1.25, max_moisture_pct: 0.01,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.53 },
  { abbrev: "PC/SAN",       name: "Polycarbonate/SAN Blend",                  bulk_density: 1.22, max_moisture_pct: 0.05,  temp_min: 100, temp_max: 110, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.62 },
  { abbrev: "PCT GF30",     name: "Polycyclohexylene Terephthalate GF30",     bulk_density: 1.63, max_moisture_pct: 0.03,  temp_min: 95,  temp_max: 95,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.80 },
  { abbrev: "PCT-G",        name: "PET-G Polycyclohexylene Terephthalate",    bulk_density: 1.23, max_moisture_pct: 0.03,  temp_min: 75,  temp_max: 75,  drying_time_min: 6.0, drying_time_max: 6.0,  specific_air_volume: 2.58 },
  { abbrev: "PE",           name: "Polyethylene",                              bulk_density: 0.94, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 1.0, drying_time_max: 2.0,  specific_air_volume: 1.05 },
  { abbrev: "PEC",          name: "Polyethylene Carbonate",                   bulk_density: 1.20, max_moisture_pct: 0.02,  temp_min: 130, temp_max: 130, drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 1.93 },
  { abbrev: "PEEK",         name: "Polyether Ether Ketone",                   bulk_density: 1.32, max_moisture_pct: 0.05,  temp_min: 150, temp_max: 150, drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.84 },
  { abbrev: "PEI",          name: "Polyetherimide",                           bulk_density: 1.27, max_moisture_pct: 0.02,  temp_min: 150, temp_max: 150, drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.51 },
  { abbrev: "PEK",          name: "Polyether Ketone",                         bulk_density: 1.30, max_moisture_pct: 0.05,  temp_min: 150, temp_max: 150, drying_time_min: 3.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PES",          name: "Polyethersulfone",                         bulk_density: 1.37, max_moisture_pct: 0.05,  temp_min: 130, temp_max: 150, drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 1.48 },
  { abbrev: "PET",          name: "Polyethylene Terephthalate",               bulk_density: 1.38, max_moisture_pct: 0.02,  temp_min: 110, temp_max: 130, drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 1.97 },
  { abbrev: "PET-G",        name: "PET Glycol Modified",                      bulk_density: 1.27, max_moisture_pct: 0.02,  temp_min: 70,  temp_max: 70,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 2.51 },
  { abbrev: "PET-Preform",  name: "PET Preform Grade",                        bulk_density: 1.39, max_moisture_pct: 0.004, temp_min: 165, temp_max: 175, drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 2.42 },
  { abbrev: "PI",           name: "Polyimide",                                bulk_density: 1.43, max_moisture_pct: 0.05,  temp_min: 175, temp_max: 175, drying_time_min: 3.0, drying_time_max: 3.0,  specific_air_volume: 1.60 },
  { abbrev: "PMMA",         name: "Polymethyl Methacrylate",                  bulk_density: 1.19, max_moisture_pct: 0.05,  temp_min: 80,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.69 },
  { abbrev: "POM",          name: "Polyoxymethylene",                         bulk_density: 1.42, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 1.0, drying_time_max: 2.0,  specific_air_volume: 1.09 },
  { abbrev: "PP",           name: "Polypropylene",                            bulk_density: 0.90, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 1.0, drying_time_max: 2.0,  specific_air_volume: 1.08 },
  { abbrev: "PP schwarz",   name: "Polypropylene Black",                      bulk_density: 1.03, max_moisture_pct: 0.05,  temp_min: 105, temp_max: 105, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.42 },
  { abbrev: "PP Talkum",    name: "Polypropylene Talcum Filled",              bulk_density: 0.95, max_moisture_pct: 0.04,  temp_min: 100, temp_max: 110, drying_time_min: 3.0, drying_time_max: 3.0,  specific_air_volume: 1.66 },
  { abbrev: "PPA",          name: "Polyphthalamide",                          bulk_density: 1.43, max_moisture_pct: 0.06,  temp_min: 120, temp_max: 120, drying_time_min: 4.0, drying_time_max: 4.0,  specific_air_volume: 1.66 },
  { abbrev: "PPE/PPO",      name: "Polyphenylene Ether/Oxide",                bulk_density: 1.08, max_moisture_pct: 0.05,  temp_min: 110, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.79 },
  { abbrev: "PPE/SB",       name: "PPE/Styrene Butadiene Blend",              bulk_density: 1.06, max_moisture_pct: 0.08,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 2.0,  specific_air_volume: 1.70 },
  { abbrev: "PPS",          name: "Polyphenylene Sulfide",                    bulk_density: 1.34, max_moisture_pct: 0.02,  temp_min: 130, temp_max: 150, drying_time_min: 3.0, drying_time_max: 4.0,  specific_air_volume: 1.48 },
  { abbrev: "PPSU",         name: "Polyphenylsulfone",                        bulk_density: 1.29, max_moisture_pct: 0.10,  temp_min: 130, temp_max: 150, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.48 },
  { abbrev: "PS",           name: "Polystyrene",                              bulk_density: 1.05, max_moisture_pct: 0.20,  temp_min: 80,  temp_max: 80,  drying_time_min: 1.0, drying_time_max: 2.0,  specific_air_volume: 1.10 },
  { abbrev: "PSU",          name: "Polysulfone",                              bulk_density: 1.25, max_moisture_pct: 0.05,  temp_min: 140, temp_max: 160, drying_time_min: 3.0, drying_time_max: 5.0,  specific_air_volume: 1.75 },
  { abbrev: "PUR",          name: "Polyurethane",                             bulk_density: 1.25, max_moisture_pct: 0.02,  temp_min: 90,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.86 },
  { abbrev: "PVC",          name: "Polyvinyl Chloride",                       bulk_density: 1.40, max_moisture_pct: 0.20,  temp_min: 60,  temp_max: 70,  drying_time_min: 1.0, drying_time_max: 3.0,  specific_air_volume: 1.40 },
  { abbrev: "SAN",          name: "Styrene Acrylonitrile",                    bulk_density: 1.08, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.49 },
  { abbrev: "SB",           name: "Styrene Butadiene",                        bulk_density: 1.05, max_moisture_pct: 0.05,  temp_min: 60,  temp_max: 80,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.52 },
  { abbrev: "SMMA",         name: "Styrene Methyl Methacrylate",              bulk_density: 1.08, max_moisture_pct: 0.20,  temp_min: 80,  temp_max: 80,  drying_time_min: 2.0, drying_time_max: 2.0,  specific_air_volume: 1.20 },
  { abbrev: "TPE-A",        name: "Thermoplastic Elastomer Amide",            bulk_density: 1.03, max_moisture_pct: 0.10,  temp_min: 65,  temp_max: 75,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 2.21 },
  { abbrev: "TPE-E",        name: "Thermoplastic Elastomer Ester",            bulk_density: 1.20, max_moisture_pct: 0.04,  temp_min: 100, temp_max: 110, drying_time_min: 3.0, drying_time_max: 4.0,  specific_air_volume: 1.82 },
  { abbrev: "TPE-O",        name: "Thermoplastic Elastomer Olefin",           bulk_density: 0.91, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 80,  drying_time_min: 1.0, drying_time_max: 2.0,  specific_air_volume: 1.36 },
  { abbrev: "TPE-S",        name: "Thermoplastic Elastomer Styrene",          bulk_density: 0.93, max_moisture_pct: 0.10,  temp_min: 90,  temp_max: 90,  drying_time_min: 1.0, drying_time_max: 1.0,  specific_air_volume: 1.00 },
  { abbrev: "TPE-U",        name: "Thermoplastic Polyurethane",               bulk_density: 1.21, max_moisture_pct: 0.05,  temp_min: 100, temp_max: 110, drying_time_min: 2.0, drying_time_max: 2.0,  specific_air_volume: 1.50 },
  { abbrev: "TPE-V",        name: "Thermoplastic Vulcanizate",                bulk_density: 0.93, max_moisture_pct: 0.08,  temp_min: 80,  temp_max: 80,  drying_time_min: 2.0, drying_time_max: 3.0,  specific_air_volume: 1.65 },
  // ── Bioplastics & special materials ─────────────────────────────────────
  { abbrev: "CA",             name: "Cellulose Acetate",                       bulk_density: 1.30, max_moisture_pct: 0.15,  temp_min: 60,  temp_max: 70,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.89 },
  { abbrev: "CP",             name: "Cellulose Propionate",                    bulk_density: 1.20, max_moisture_pct: 0.15,  temp_min: 60,  temp_max: 80,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.81 },
  { abbrev: "PA 10.10",       name: "Polyamide 10.10 Bio-based",               bulk_density: 1.05, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 10.10-GF30",  name: "PA 10.10 Glass Fiber 30%",               bulk_density: 1.29, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 10.12",       name: "Polyamide 10.12 Bio-based",               bulk_density: 1.03, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 10.12-GF30",  name: "PA 10.12 Glass Fiber 30%",               bulk_density: 1.25, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 11 (bio)",    name: "Polyamide 11 Bio-based",                  bulk_density: 1.02, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 12 (bio)",    name: "Polyamide 12 Bio-based",                  bulk_density: 1.01, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.95 },
  { abbrev: "PA 4.10",        name: "Polyamide 4.10",                          bulk_density: 1.08, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 2.38 },
  { abbrev: "PA 4.10-GF30",   name: "PA 4.10 Glass Fiber 30%",                bulk_density: 1.34, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 2.29 },
  { abbrev: "PA 4.10-GF50",   name: "PA 4.10 Glass Fiber 50%",                bulk_density: 1.52, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 90,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 2.21 },
  { abbrev: "PA 6.10",        name: "Polyamide 6.10",                          bulk_density: 1.06, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 110, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 2.38 },
  { abbrev: "PA 6.10-GF30",   name: "PA 6.10 Glass Fiber 30%",                bulk_density: 1.32, max_moisture_pct: 0.10,  temp_min: 80,  temp_max: 110, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 2.29 },
  { abbrev: "PBAT",           name: "Polybutylene Adipate Terephthalate",      bulk_density: 1.25, max_moisture_pct: 0.08,  temp_min: 80,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.78 },
  { abbrev: "PBS/PBSA",       name: "Polybutylene Succinate/Adipate",          bulk_density: 1.26, max_moisture_pct: 0.10,  temp_min: 70,  temp_max: 80,  drying_time_min: 3.0, drying_time_max: 4.0,  specific_air_volume: 1.72 },
  { abbrev: "PCL-Wax-Blend",  name: "Polycaprolactone Wax Blend",             bulk_density: 1.05, max_moisture_pct: 0.20,  temp_min: 45,  temp_max: 50,  drying_time_min: 6.0, drying_time_max: 8.0,  specific_air_volume: 2.02 },
  { abbrev: "PEBA",           name: "Polyether Block Amide",                   bulk_density: 1.03, max_moisture_pct: 0.20,  temp_min: 65,  temp_max: 75,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 1.92 },
  { abbrev: "PHB/PHA",        name: "Polyhydroxybutyrate/Alkanoate",           bulk_density: 1.25, max_moisture_pct: 0.03,  temp_min: 50,  temp_max: 60,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 1.84 },
  { abbrev: "PLA",            name: "Polylactic Acid",                         bulk_density: 1.25, max_moisture_pct: 0.025, temp_min: 60,  temp_max: 90,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.77 },
  { abbrev: "PLA-A",          name: "Polylactic Acid Amorphous",               bulk_density: 1.25, max_moisture_pct: 0.025, temp_min: 50,  temp_max: 50,  drying_time_min: 8.0, drying_time_max: 12.0, specific_air_volume: 2.03 },
  { abbrev: "PLA Preform",    name: "PLA Preform Grade",                       bulk_density: 1.25, max_moisture_pct: 0.01,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 6.0,  specific_air_volume: 2.06 },
  { abbrev: "PLA/PBAT",       name: "PLA/PBAT Blend",                         bulk_density: 1.47, max_moisture_pct: 0.08,  temp_min: 80,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 5.0,  specific_air_volume: 1.77 },
  { abbrev: "PLA Folien",     name: "PLA Film Grade",                         bulk_density: 1.26, max_moisture_pct: 0.20,  temp_min: 60,  temp_max: 60,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.67 },
  { abbrev: "PLA schlagzäh",  name: "Impact-Modified PLA",                    bulk_density: 1.24, max_moisture_pct: 0.10,  temp_min: 50,  temp_max: 50,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.97 },
  { abbrev: "PLA/TPC",        name: "PLA/TPC Blend",                          bulk_density: 1.30, max_moisture_pct: 0.30,  temp_min: 60,  temp_max: 60,  drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.58 },
  { abbrev: "PPA (bio)",      name: "Polyphthalamide Bio-based",               bulk_density: 1.13, max_moisture_pct: 0.10,  temp_min: 70,  temp_max: 80,  drying_time_min: 4.0, drying_time_max: 8.0,  specific_air_volume: 1.75 },
  { abbrev: "PTT",            name: "Polytrimethylene Terephthalate",          bulk_density: 1.32, max_moisture_pct: 0.02,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.92 },
  { abbrev: "PTT-GF15",       name: "PTT Glass Fiber 15%",                    bulk_density: 1.40, max_moisture_pct: 0.02,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.83 },
  { abbrev: "PTT-GF30",       name: "PTT Glass Fiber 30%",                    bulk_density: 1.56, max_moisture_pct: 0.02,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.75 },
  { abbrev: "PTT-GF45",       name: "PTT Glass Fiber 45%",                    bulk_density: 1.74, max_moisture_pct: 0.02,  temp_min: 120, temp_max: 120, drying_time_min: 2.0, drying_time_max: 4.0,  specific_air_volume: 1.67 },
  { abbrev: "TPS",            name: "Thermoplastic Starch",                   bulk_density: 1.25, max_moisture_pct: 0.20,  temp_min: 50,  temp_max: 50,  drying_time_min: 4.0, drying_time_max: 6.0,  specific_air_volume: 1.79 },
  { abbrev: "WPC PE",         name: "Wood-Plastic Composite PE",              bulk_density: 0.96, max_moisture_pct: 0.40,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 5.0,  specific_air_volume: 1.90 },
  { abbrev: "WPC PE Extr.",   name: "Wood-Plastic Composite PE Extrusion",    bulk_density: 0.96, max_moisture_pct: 1.50,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 5.0,  specific_air_volume: 1.90 },
  { abbrev: "WPC PLA",        name: "Wood-Plastic Composite PLA",             bulk_density: 0.92, max_moisture_pct: 0.20,  temp_min: 50,  temp_max: 50,  drying_time_min: 5.0, drying_time_max: 5.0,  specific_air_volume: 1.62 },
  { abbrev: "WPC PLA Extr.",  name: "Wood-Plastic Composite PLA Extrusion",   bulk_density: 0.92, max_moisture_pct: 0.50,  temp_min: 50,  temp_max: 50,  drying_time_min: 5.0, drying_time_max: 5.0,  specific_air_volume: 1.62 },
  { abbrev: "WPC PP",         name: "Wood-Plastic Composite PP",              bulk_density: 0.90, max_moisture_pct: 0.40,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 5.0,  specific_air_volume: 1.90 },
  { abbrev: "WPC PP Extr.",   name: "Wood-Plastic Composite PP Extrusion",    bulk_density: 0.90, max_moisture_pct: 1.50,  temp_min: 80,  temp_max: 100, drying_time_min: 2.0, drying_time_max: 5.0,  specific_air_volume: 1.96 },
  { abbrev: "WPC TPS",        name: "Wood-Plastic Composite TPS",             bulk_density: 0.92, max_moisture_pct: 0.20,  temp_min: 50,  temp_max: 50,  drying_time_min: 5.0, drying_time_max: 5.0,  specific_air_volume: 1.79 },
  { abbrev: "WPC TPS Extr.",  name: "Wood-Plastic Composite TPS Extrusion",   bulk_density: 0.92, max_moisture_pct: 0.50,  temp_min: 50,  temp_max: 50,  drying_time_min: 5.0, drying_time_max: 5.0,  specific_air_volume: 1.79 },
];
